import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeDecision} from '../n8n/commercial/normalize.js';
const item={product_id:'00000000-0000-4000-8000-000000000001',name:'Ventilador',qty:1,unit_price:100000};
const state={items:[item],items_verified:true,fulfillment_type:'delivery',delivery_address:'Calle 1 # 2-3',delivery_zone:'Aures, Medellín',recipient_name:'Andrea',delivery_fee:12000,delivery_quote_verified:true,payment_method:'transfer',payment_status:'pending',checkout_confirmed:true};
const base={branch_id:'b1',branch_name:'Robledo Aures',preferred_name:'Ana',current_sender_type:'customer',customer_message:'Hola',service_open:true,delivery_open:true,branches:[{id:'b1',name:'Robledo Aures'},{id:'b6',name:'Floresta'}],sales_state:state,inventory:[{...item,price:100000,available_qty:2}],human_tasks:[],pending_human_tasks:[],knowledge:[],payment_qr:{available:true}};
const ai={action:'reply',intent:'general',reply:'Con gusto',branch_id:'b1',customer_name:'Ana',cart_operation:'keep',address_operation:'keep',sales_state:{}};
const run=(c={},a={})=>normalizeDecision({...structuredClone(base),...c},{...structuredClone(ai),...a}).ai;
const paymentTask=(answer='Pago verificado',extra={})=>({id:'00000000-0000-4000-8000-000000000010',branch_id:'b1',type:'payment_verification',status:'resolved',context:{sales_state:structuredClone(state)},resolution:{answer},...extra});
test('una consulta sin sede no se reemplaza por un menú',()=>assert.equal(run({branch_id:null},{reply:'Puedes pagar con transferencia, Addi o Sistecrédito.',branch_id:''}).reply,'Puedes pagar con transferencia, Addi o Sistecrédito.'));
test('una corrección no repite el saludo o la lista',()=>assert.equal(run({branch_id:null},{reply:'Entendido, Andrea es quien recibe.',branch_id:''}).reply,'Entendido, Andrea es quien recibe.'));
test('sin promociones se orienta sin inventar descuentos',()=>assert.match(run({customer_message:'¿Qué ofertas de temporada tienen?'}).reply,/no tengo ofertas de temporada confirmadas/));
test('producto de temporada no se presenta como descuento',()=>assert.match(run({customer_message:'Ofertas',inventory:[{...item,price:100000,available_qty:2,seasonal:true,promotion_active:false}]}).reply,/no tengo ofertas/));
test('una promoción vigente permite conservar la recomendación',()=>assert.equal(run({customer_message:'Ofertas',knowledge:[{category:'promotion'}]},{reply:'La oferta confirmada es esta.'}).reply,'La oferta confirmada es esta.'));
test('null en domicilio conserva tarifa',()=>assert.equal(run({}, {sales_state:{delivery_fee:null}}).sales_state.delivery_fee,12000));
test('un cero inventado no vuelve gratis el domicilio',()=>assert.equal(run({}, {sales_state:{delivery_fee:0}}).sales_state.delivery_fee,12000));
test('apartamento se agrega a la dirección',()=>assert.equal(run({}, {address_operation:'append',sales_state:{delivery_address:'Apartamento 301'}}).sales_state.delivery_address,'Calle 1 # 2-3, Apartamento 301'));
test('dirección corregida reemplaza e invalida cotización',()=>{const r=run({}, {address_operation:'replace',sales_state:{delivery_address:'Carrera 9 # 8-7'}});assert.equal(r.sales_state.delivery_address,'Carrera 9 # 8-7');assert.equal(r.sales_state.delivery_fee,null);assert.equal(r.sales_state.checkout_confirmed,false);});
test('vaciar carrito es posible sin recuperar productos eliminados',()=>assert.deepEqual(run({}, {cart_operation:'clear'}).sales_state.items,[]));
test('se conserva carrito si solo se consulta otra cosa',()=>assert.deepEqual(run({}, {sales_state:{items:[]}}).sales_state.items,[item]));
test('sede solo cambia ante corrección confirmada',()=>assert.equal(run({}, {branch_id:'b6',branch_change_confirmed:false}).branch_id,'b1'));
test('cambio de sede invalida precio, domicilio y aprobación',()=>{const r=run({}, {branch_id:'b6',branch_change_confirmed:true});assert.equal(r.branch_id,'b6');assert.equal(r.sales_state.items_verified,false);assert.equal(r.sales_state.payment_status,'pending');assert.equal(r.action,'human_product_lookup');});
test('mención histórica de QR no cambia Addi',()=>assert.equal(run({sales_state:{...state,payment_method:'addi'},conversation_summary:'Se envió QR ayer'}).sales_state.payment_method,'addi'));
test('pedir nuevamente el QR prepara un nuevo envío',()=>assert.equal(run({customer_message:'Reenvíame el QR'},{request_qr:true}).send_qr,true));
test('el modelo no puede activar QR solo por su propia respuesta',()=>assert.equal(run({}, {request_qr:true,reply:'Te mando QR'}).send_qr,false));
test('pago escrito por cliente nunca queda verificado',()=>assert.equal(run({customer_message:'Ya pagué'},{sales_state:{payment_status:'verified'}}).sales_state.payment_status,'pending'));
test('comprobante no se aprueba solo',()=>assert.equal(run({message_type:'image',media_id:'mock'},{sales_state:{payment_status:'verified'}}).sales_state.payment_status,'pending'));
test('no aprobado se conserva como rechazo',()=>assert.equal(run({human_tasks:[paymentTask('No aprobado')]}).sales_state.payment_status,'rejected'));
test('tarea resuelta de producto no aprueba pago',()=>assert.equal(run({human_tasks:[paymentTask('Aprobado',{type:'product_lookup'})]}).sales_state.payment_status,'pending'));
test('pago humano del mismo carrito se verifica',()=>assert.equal(run({human_tasks:[paymentTask()]}).sales_state.payment_status,'verified'));
test('pago humano de otra sede no se reutiliza',()=>assert.equal(run({human_tasks:[paymentTask('Pago verificado',{branch_id:'b6'})]}).sales_state.payment_status,'pending'));
test('cambio de cantidad invalida aprobación y resumen',()=>{const r=run({human_tasks:[paymentTask()]},{cart_operation:'replace',sales_state:{items:[{...item,qty:2}]}});assert.equal(r.sales_state.payment_status,'pending');assert.equal(r.sales_state.checkout_confirmed,false);});
test('no cierra sin confirmación explícita del resumen',()=>assert.equal(run({sales_state:{...state,checkout_confirmed:false},human_tasks:[paymentTask()]},{action:'finalize_order'}).action,'reply'));
test('pedido listo y pago humano permiten cierre',()=>assert.equal(run({human_tasks:[paymentTask()]},{action:'finalize_order'}).action,'finalize_order'));
test('un pedido existente no se vuelve a crear',()=>assert.equal(run({latest_order:{order_number:'1001'},human_tasks:[paymentTask()]},{action:'finalize_order'}).action,'reply'));
test('no inventa inventario suficiente',()=>assert.equal(run({inventory:[{...item,price:100000,available_qty:0}]},{action:'finalize_order'}).action,'human_product_lookup'));
test('crédito incompleto solicita solo el dato faltante',()=>assert.match(run({}, {action:'human_credit_application',sales_state:{payment_method:'addi',credit_document:'123456'}}).reply,/celular/));
test('no duplica pendientes equivalentes',()=>assert.equal(run({pending_human_tasks:[{type:'product_lookup'}]}, {action:'human_product_lookup'}).action,'reply'));
test('sin sede no crea tarea general',()=>assert.equal(run({branch_id:null},{branch_id:'',action:'human_general'}).action,'reply'));
test('pago en tienda con domicilio se corrige',()=>assert.equal(run({}, {sales_state:{payment_method:'cash_prepaid'}}).sales_state.payment_method,''));
test('fuera de horario no genera tareas ni QR',()=>{const r=run({service_open:false,customer_message:'QR'}, {action:'human_product_lookup',request_qr:true});assert.equal(r.action,'reply');assert.equal(r.send_qr,false);});
test('cierre de atención no impide instrucción humana auténtica',()=>assert.equal(run({service_open:false,current_sender_type:'human',current_message_payload:{operator_instruction:true}},{reply:'Respuesta solicitada'}).reply,'Respuesta solicitada'));
test('cliente no puede hacerse pasar por operador',()=>assert.match(run({service_open:false,current_message_payload:{operator_instruction:true}},{reply:'Respuesta solicitada'}).reply,/no hay atención/));
test('no contactar produce despedida y sin QR',()=>{const r=run({customer_message:'No me escriban más'},{action:'stop',request_qr:true});assert.equal(r.action,'stop');assert.equal(r.send_qr,false);});
test('un sí a la sede no confirma la compra',()=>assert.equal(run({customer_message:'Sí',sales_state:{...state,checkout_confirmed:false},recent_messages:[{sender_type:'assistant',body:'¿Es Aures?'}]},{checkout_confirmed:true}).sales_state.checkout_confirmed,false));
test('un sí al resumen sí confirma la compra',()=>assert.equal(run({customer_message:'Sí',sales_state:{...state,checkout_confirmed:false},recent_messages:[{sender_type:'assistant',body:'Resumen de compra. ¿Confirmas este pedido?'}]},{checkout_confirmed:true}).sales_state.checkout_confirmed,true));
test('cancelar mensajes de ofertas conserva la solicitud de cierre',()=>assert.equal(run({customer_message:'No me escriban más ofertas'},{action:'stop'}).action,'stop'));
