import {useCallback,useEffect,useState} from 'react';
import {uploadBotImage,listBotImages,botImageUrl,hideBotImage} from './lib/api.js';
export default function BotImages({kind,branchId,productId,taskId,onChange}){
 const [rows,setRows]=useState([]),[file,setFile]=useState(null),[caption,setCaption]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const reload=useCallback(async()=>{try{const records=await listBotImages({kind,...(productId?{product_id:productId,branch_id:branchId}:{}),...(taskId?{task_id:taskId}:{})});setRows(await Promise.all(records.map(async r=>({...r,url:await botImageUrl(r.storage_path)}))));}catch(e){setError(e.message);}},[kind,branchId,productId,taskId]);
 useEffect(()=>{reload();},[reload]);
 async function upload(){setBusy(true);setError('');try{const asset=await uploadBotImage({kind,branch_id:branchId,product_id:productId,task_id:taskId,caption},file);setFile(null);setCaption('');await reload();onChange?.(asset);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function hide(id){setBusy(true);try{await hideBotImage(id);await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="bot-images"><h4>Imágenes para el cliente</h4><p className="form-note">Identifica el producto o la variante en cada foto. JPG o PNG, hasta 5 MB. Se enviarán hasta 2 por respuesta.</p><div className="bot-image-grid">{rows.map(r=><figure key={r.id}><a href={r.url} target="_blank" rel="noreferrer"><img src={r.url} alt={r.caption}/></a><figcaption>{r.caption}</figcaption><button type="button" disabled={busy} onClick={()=>hide(r.id)}>Retirar</button></figure>)}</div>{rows.length<3&&<><label>Fotografía<input type="file" accept="image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Producto que muestra<input maxLength={500} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Ej. Disfraz Superman, unitalla, vista frontal"/></label><button type="button" disabled={busy||!file||!caption.trim()} onClick={upload}>{busy?'Subiendo…':'Guardar imagen'}</button></>}{error&&<p role="alert" className="operator-error">{error}</p>}</section>;
}
