import {useCallback,useEffect,useState} from 'react';
import {campaignRequest,listCampaigns,listCampaignRecipients,uploadBotImage,botImageUrl} from './lib/api.js';
import {formatDateTime} from './lib/constants.js';
const labels={draft:'Borrador',queued:'En envío',completed:'Procesada',cancelled:'Detenida',pending:'Pendiente',sending:'Enviando',sent:'Enviado',delivered:'Entregado',read:'Leído',failed:'Falló',uncertain:'Por revisar',skipped:'Excluido'};
export default function WhatsappCampaigns({contacts}){
 const [data,setData]=useState({campaigns:[],totals:[],permissions:[],flyers:[]}),[templates,setTemplates]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[asset,setAsset]=useState(''),[file,setFile]=useState(null),[templateKey,setTemplateKey]=useState(''),[values,setValues]=useState([]),[phones,setPhones]=useState(''),[selected,setSelected]=useState([]),[permission,setPermission]=useState(false),[evidence,setEvidence]=useState(''),[review,setReview]=useState(null),[image,setImage]=useState(''),[details,setDetails]=useState(null),[recipients,setRecipients]=useState([]),[reviewImage,setReviewImage]=useState('');
 const recipientCampaign=review||details;
 useEffect(()=>{let active=true;setRecipients([]);if(recipientCampaign)listCampaignRecipients(recipientCampaign).then(rows=>{if(active)setRecipients(rows);}).catch(e=>setError(e.message));return()=>{active=false;};},[recipientCampaign,data]);
 useEffect(()=>{let active=true;setReviewImage('');const c=data.campaigns.find(c=>c.id===review),a=data.flyers.find(a=>a.id===c?.asset_id);if(a)botImageUrl(a.storage_path).then(url=>{if(active)setReviewImage(url);}).catch(e=>setError(e.message));return()=>{active=false;};},[review,data]);
 const template=templates.find(t=>`${t.name}:${t.language}`===templateKey);
 const refresh=useCallback(async()=>{try{setData(await listCampaigns());}catch(e){setError(e.message);}},[]);
 useEffect(()=>{refresh();campaignRequest().then(d=>setTemplates(d.templates)).catch(e=>setError(e.message));const t=setInterval(refresh,10000);return()=>clearInterval(t);},[refresh]);
 useEffect(()=>{let alive=true;const a=data.flyers.find(a=>a.id===asset);if(a)botImageUrl(a.storage_path).then(url=>{if(alive)setImage(url);}).catch(e=>setError(e.message));else setImage('');return()=>{alive=false;};},[asset,data.flyers]);
 async function upload(){setBusy(true);setError('');try{const a=await uploadBotImage({kind:'flyer',caption:name||'Flyer publicitario'},file);await refresh();setAsset(a.id);setFile(null);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function prepare(e){e.preventDefault();setBusy(true);setError('');try{const result=await campaignRequest({action:'prepare',name,asset_id:asset,template_name:template.name,language:template.language,values,phones:[...selected,...phones.split(/[,;\n]+/).map(s=>s.trim()).filter(Boolean)],permission_confirmed:permission,permission_evidence:evidence});await refresh();setReview(result.id);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function act(action,id){setBusy(true);setError('');try{await campaignRequest({action,id});setReview(null);await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const reviewing=data.campaigns.find(c=>c.id===review);const targets=reviewing?recipients.filter(r=>r.campaign_id===review):[];
 const permissionFor=p=>data.permissions.find(x=>x.phone_e164===p)?.status;
 return <div className="campaigns"><p>Envía un flyer con una plantilla de publicidad aprobada. Selecciona destinatarios con autorización; escribirnos por una compra no los suscribe a publicidad. Los envíos pueden generar cargos de Meta.</p>{error&&<p role="alert" className="operator-error">{error}</p>}
 <div className="chat-manager"><form className="panel knowledge-form" onSubmit={prepare}><h3>Nueva campaña</h3><label>Nombre interno<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Flyer guardado<select required value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Seleccionar imagen</option>{data.flyers.map(a=><option key={a.id} value={a.id}>{a.caption} · {a.original_name}</option>)}</select></label>{image&&<img className="campaign-flyer" src={image} alt="Flyer seleccionado"/>}<label>Subir flyer<input type="file" accept="image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button type="button" disabled={busy||!file} onClick={upload}>Guardar flyer</button>
 <label>Plantilla aprobada<select required value={templateKey} onChange={e=>{setTemplateKey(e.target.value);const t=templates.find(t=>`${t.name}:${t.language}`===e.target.value);setValues(Array(t?.variables||0).fill(''));}}><option value="">Seleccionar plantilla</option>{templates.map(t=><option key={`${t.name}:${t.language}`} value={`${t.name}:${t.language}`}>{t.name} · {t.language}</option>)}</select></label>{!templates.length&&<p className="form-note">No hay plantillas compatibles disponibles. En WhatsApp Manager crea una plantilla de Marketing con encabezado de imagen; cuando Meta la apruebe, recarga esta sección.</p>}
 {template&&<><p className="campaign-preview">{template.body.replace(/\{\{(\d+)\}\}/g,(_,n)=>values[n-1]||`[Texto ${n}]`)}</p>{values.map((v,i)=><label key={i}>Texto {i+1}<input required maxLength={500} value={v} onChange={e=>setValues(values.map((x,j)=>j===i?e.target.value:x))}/></label>)}<small>{template.footer}</small><p className="form-note">Incluye «Responde BAJA para dejar de recibir publicidad» en un texto de la plantilla, o utiliza su botón de baja.</p></>}
 <label>Números adicionales<textarea value={phones} onChange={e=>setPhones(e.target.value)} placeholder="Un teléfono por línea. Puedes usar móviles colombianos o el prefijo internacional."/></label>
 <label className="check"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)}/> Tengo autorización de los destinatarios seleccionados para enviarles publicidad de El Rey por WhatsApp.</label>{permission&&<label>Cómo y cuándo autorizaron<input required minLength={8} maxLength={500} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Ej. Formulario de suscripción, fecha y referencia"/></label>}<p className="form-note">Las bajas quedan excluidas aunque marques esta casilla. Sin autorización guardada ni confirmada, el número se excluye.</p><button className="primary" disabled={busy||!template||!asset}>{busy?'Preparando…':'Revisar campaña'}</button></form>
 <section className="panel knowledge-list"><h3>Clientes que ya nos escribieron</h3><button onClick={()=>setSelected(contacts.filter(c=>c.phone_e164&&permissionFor(c.phone_e164)==='granted').map(c=>c.phone_e164))}>Seleccionar todos los autorizados</button><button onClick={()=>setSelected([])}>Quitar selección</button><p>{selected.length} seleccionados</p><div className="campaign-contacts">{contacts.filter(c=>c.phone_e164).map(c=>{const state=permissionFor(c.phone_e164);return <label className="check" key={c.id}><input type="checkbox" disabled={state==='revoked'} checked={selected.includes(c.phone_e164)} onChange={e=>setSelected(e.target.checked?[...selected,c.phone_e164]:selected.filter(p=>p!==c.phone_e164))}/><span>{c.preferred_name||c.display_name||'Cliente'} · {c.phone_e164}<small>{state==='revoked'?'Baja registrada':state==='granted'?'Publicidad autorizada':'Sin autorización de publicidad registrada'}</small></span></label>;})}</div></section></div>
 {reviewing&&<section className="panel campaign-review"><h3>Revisar antes de enviar: {reviewing.name}</h3>{reviewImage&&<img className="campaign-flyer" src={reviewImage} alt="Flyer de esta campaña"/>}<p className="campaign-preview">{reviewing.template.preview}</p><p>{reviewing.template.footer}</p><p><strong>{targets.length} destinatarios autorizados</strong>. {reviewing.excluded_count} números excluidos por falta de permiso o baja.</p><details><summary>Ver números</summary>{targets.map(r=><p key={r.id}>{r.phone_e164}</p>)}</details><button className="primary" disabled={busy||!targets.length||!reviewImage} onClick={()=>act('start',review)}>Enviar campaña a {targets.length} destinatarios</button><button onClick={()=>setReview(null)}>Guardar como borrador</button></section>}
 <section className="panel knowledge-list"><h3>Campañas guardadas</h3>{data.campaigns.map(c=>{const rows=recipients.filter(r=>r.campaign_id===c.id),totals=data.totals.filter(r=>r.campaign_id===c.id);return <article key={c.id}><div><b>{c.name}</b><span>{labels[c.status]} · {formatDateTime(c.created_at)}</span><small>{totals.map(r=>`${labels[r.status]}: ${r.count}`).join(' · ')}</small></div>{c.status==='draft'&&<button onClick={()=>setReview(c.id)}>Revisar</button>}{['draft','queued'].includes(c.status)&&<button disabled={busy} onClick={()=>act('cancel',c.id)}>Detener</button>}<button onClick={()=>setDetails(details===c.id?null:c.id)}>Resultados</button>{details===c.id&&<div className="campaign-results">{rows.map(r=><p key={r.id}>{r.phone_e164} · {labels[r.status]}{r.error?` · ${r.error}`:''}</p>)}</div>}</article>;})}</section></div>;
}
